<?php
$generos = [
    "Ação",
    "Aventura",
    "Biografia",
    "Chick-lit",
    "Clássico",
    "Comédia",
    "Conto",
    "Crônica",
    "Didático",
    "Distopia",
    "Drama",
    "Ensaios",
    "Epistolar",
    "Erótico",
    "Fantasia",
    "Ficção Científica",
    "Ficção Histórica",
    "Filosofia",
    "Guerra",
    "História",
    "Horror",
    "Humor",
    "Infantojuvenil",
    "Investigação",
    "Jovem Adulto (YA)",
    "Literatura Brasileira",
    "Literatura Estrangeira",
    "Literatura Infantil",
    "LGBTQIA+",
    "Mistério",
    "Musical",
    "Poesia",
    "Policial",
    "Psicologia",
    "Realismo Mágico",
    "Religião / Espiritualidade",
    "Romance",
    "Romance de Época",
    "Romance Policial",
    "Romance Histórico",
    "Romance Sobrenatural",
    "Sátira",
    "Suspense",
    "Terror",
    "Thriller",
    "Western (Faroeste)",
    "Outros"
];

?>